<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE cartelera [
<!ELEMENT cartelera ((peliculas, cines)|(cines,peliculas))>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (titulo, anyo, director, id)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT cines (cine+)>
<!ELEMENT cine (nombre, sala, peli, sesiones)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT sala (#PCDATA)>
<!ELEMENT peli (#PCDATA)>
<!ELEMENT sesiones (sesion+)>
<!ELEMENT sesion (#PCDATA)>
]>

<cartelera>

	<peliculas>

		<pelicula>
			<titulo>La invencion de Hugo</titulo>
			<anyo>2011</anyo>
			<director>Martin Scorsese</director>
			<id>20097</id>
		</pelicula>

		<pelicula>
			<titulo>John Carter</titulo>
			<anyo>2012</anyo>
			<director>Andrew Stanton</director>
			<id>322587</id>
		</pelicula>

		<pelicula>
			<titulo>Intocable</titulo>
			<anyo>2011</anyo>
			<director>Olivier Nakache</director>
			<id>688879</id>
		</pelicula>

	</peliculas>


	<cines>

		<cine>
			<nombre>ABC El Saler</nombre>
			<sala>Sala 6</sala>
			<peli>La invenci√≥n de Hugo</peli>
			<sesiones>
				<sesion>18:00</sesion>
				<sesion>20:25</sesion>
				<sesion>22:50</sesion>
			</sesiones>
		</cine>

		<cine>
			<nombre>Lys</nombre>
			<sala>. Sala 3</sala>
			<peli>John Carter</peli>
			<sesiones>
				<sesion>16:20</sesion>
				<sesion>18:50</sesion>
			</sesiones>
		</cine>

	</cines>

</cartelera>

