<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE softwareLibre [  
<!ELEMENT softwareLibre (licencias, aplicaciones)>  
<!ELEMENT licencias (licencia*)>   
<!ELEMENT licencia EMPTY>   
<!ELEMENT aplicaciones (aplicacion*)>   
<!ELEMENT aplicacion (version*)>   
<!ELEMENT version EMPTY>   
<!ATTLIST licencia nombre ID #REQUIRED>   
<!ATTLIST aplicacion nombre NMTOKEN #REQUIRED>   
<!ATTLIST version nombre NMTOKEN #REQUIRED>   
<!ATTLIST version licencia IDREF #REQUIRED>   
<!ATTLIST version fechaPublicacion CDATA #REQUIRED> ]> 


<softwareLibre>   

	<licencias>     
		<licencia nombre="GPLv2"/>    
		<licencia nombre="BSD2"/>    
		<licencia nombre="Apachev2"/>  
	</licencias> 


	<aplicaciones>     
		<aplicacion nombre="Inkscape">     
			<version nombre="0.47" licencia="GPLv2" fechaPublicacion="17/08/2010"/>      
			<version nombre="0.48" licencia="GPLv2" fechaPublicacion="17/08/2010"/>      
			<version nombre="0.48.2" licencia="GPLv2" fechaPublicacion="14/08/2011"/>    
		</aplicacion>

		<aplicacion nombre="PostgreSQL">      
			<version nombre="9.1.0" licencia="GPLv2" fechaPublicacion="15/09/2011"/>      
			<version nombre="9.1.3" licencia="GPLv2" fechaPublicacion="19/06/2012"/>    
		</aplicacion>


	</aplicaciones>   

</softwareLibre>